### ISSUE TITLE
Integrate existing encoding methods via FFI

### ISSUE THREAD

**Issue by snowleopard** [tuura/scenco#3]
We have an existing C implementation of encoding, synthesis and technology mapping algorithms. Although we intend to eventually rewrite (some of) them in Haskell, it may be useful to start by reusing existing implementation via Foreign Function Interface (calling C functions from Haskell).

**Comment by allegroCoder** [comment]
I have experimented how to use the function “createProcess” in Haskell, which is able to spawn an external process (c++ in our case), and to store the output into an handle which can be used inside the Haskell program. I have tried to use it into a smaller tool and seems to me not too difficult to exploit.

I would start splitting SCENCO into three separated tools, which we could call from Haskell program to assign the task (encoding, synthesis, technology mapping).

**Comment by allegroCoder** [comment]
I am having an issue using a c++ function inside an Haskell file.

I have got a .cpp file named "func.cpp" and a header file where the prototype of the function is defined. The function I am trying to used is simply the one below:
int myadd(int a, int b){
	return (a+b);
}

Inside the Main.hs file contained inside the scenco repository, I imported the external function using the foreign interface:

import Foreign
import Foreign.C.Types

foreign import ccall "myadd"
    c_myadd :: Int -> Int -> IO Int

As far as I understood, "c_myadd" is the name of the function I can use to call the c++ "myadd" function, defined inside the "func.cpp" file.

I compile everything using the command: "ghc --make Main.hs"
but that's the output of the compiler:

Linking Main ...
Main.o: In function `s2gY_info':
(.text+0x21e): undefined reference to `myadd'
collect2: error: ld returned 1 exit status

**Comment by snowleopard** [comment]
I got the following working.

`func.c`:
```c
int myadd(int a, int b){
    return (a+b);
}
```
`Main.hs`:
```haskell
import Foreign
import Foreign.C.Types

foreign import ccall unsafe "myadd"
    c_myadd :: Int -> Int -> IO Int

main = do
    x <- read <$> getLine
    y <- read <$> getLine
    z <- c_myadd x y
    putStrLn $ "sum = " ++ show z
```
Command line:
```
ghc --make Main.hs func.c
```
No header files needed.


Interestingly, when I switch to `func.cpp` I can't link either.

**Comment by snowleopard** [comment]
This stackoverflow thread seems relevant to the C vs C++ issue: http://stackoverflow.com/questions/12475726/haskell-ffi-interfacing-with-simple-c

**Comment by allegroCoder** [comment]
Another link which might be of interest: https://wiki.haskell.org/Cxx_foreign_function_interface
I am still figuring out how to do it.

**Comment by allegroCoder** [comment]
As this page (https://wiki.haskell.org/CPlusPlus_from_Haskell) suggest:

"According to the Foreign Function Interface section of the Haskell 2010 report -- you import a C++ function by simply specifying the calling convention cplusplus. Unfortunately, no haskell compiler actually supports this calling convention, so we have to use the C calling convention instead."

Apparently the problem is due to the compilation process, as described in the following bit:

"C++ allows you to have many methods with the same name, but different arguments. However, the underlying linker does not -- so C++ mangles the methods names to ensure that each method name is unique."

Therefore, in order to solve the problem, I used the construct `extern "C"`, in order to let the compiler know to use the C pattern. The following files named `func.cpp` and `func.h`, respectively, do the job!
```c
#include "func.h"

extern "C" myint myadd(myint a, myint b){
	return (a+b);
}
```
```c
#ifndef FUNC_H
#define FUNC_H
#include <stdio.h>
#include <stdlib.h>

typedef int myint;

#endif
```

I compile everything using the command: `ghc --make Main.hs func.cpp`.

**Comment by snowleopard** [comment]
Ah, I remember now. I actually used exactly the same approach in the `compote` project. See this file, for instance: https://github.com/tuura/compote/blob/master/src/c%2B%2B/BDD/instance.cpp.

**Comment by snowleopard** [comment]
Let me close this now, I think FFI is no longer an issue.
